### ISSUE TITLE
User Story 1 - Display Solar Activity

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#1]
## Value proposition

As a user
I want an information about the radiation of my location
So that I can know the solar activity of my place

## Description

![Bildschirm­foto 2023-04-25 um 16 10 41](https://user-images.githubusercontent.com/125971942/234303746-ae499c13-0c11-4881-ac10-d01a3daa2ed5.png)

## Acceptance criteria

- [ ] the header is displayed
- [ ] the location and radiation is displayed in a card
- [ ] the location is displayed correctly. The location will be placed through an input field in a different user story
- [ ] the radiation is displayed as dummy data for now and will show annual radiation in kWh / m2

## Tasks

- [ ] create a branch 
- [ ] create a header component
- [ ] create a card component with the dummy data

**Comment by Roland-Hufnagel** [comment]
This looks really good. Only the data storing in a database should be placed in a different userstory. Please remove it here. Then you are good to go.

**Comment by sirtobiwan** [comment]
thanks, new US was created: https://github.com/sirtobiwan/Capstone-Project-Solar-Calculator/issues/4
