### ISSUE TITLE
US-5 - Display Location

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#10]
## Value proposition

As a user
I want to see my location
in order to continue to the next page and then see the radiation data (will be implemented in a different user story)

## Description
![Bildschirm­foto 2023-05-05 um 19 08 03](https://user-images.githubusercontent.com/125971942/236522088-fd50d9e8-c154-4bee-a457-3974d340941b.png)

## Acceptance criteria

- [ ] display current location

## Tasks

- [ ] create a location component with a useState, useEffect and API connection
- [ ] display the location at the return statement

**Comment by sirtobiwan** [comment]
Thank you Mareike. I need some data from this location on the next page where it will show the radiation data based on the location. So I thought I would need the useState to drill it as a prop to another page
