### ISSUE TITLE
US-6 - Input Field of electricity costs

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#13]
## Value proposition

As a user
I want to enter the electricity costs
in order to calculate the savings

## Description

![Bildschirm­foto 2023-05-04 um 12 33 34](https://user-images.githubusercontent.com/125971942/236180197-68486e27-e8f5-4365-8502-ef71c2726a40.png)

## Acceptance criteria

- [ ] input field for electricity costs on the page "savings"
- [ ] the input field has a placeholder for average costs

## Tasks

- [ ] create an input field at a new component
- [ ] insert this component on the page "savings"

**Comment by frank12421** [comment]
Hi Tobias, 
I noticed a few things that you could still revise:

Acceptance Criteria:

- These costs will be used later to calculate savings:
This will be difficult to verify and would therefore not be an acceptance criterion in my opinion.

Tasks

- the input field should have a placeholder for average costs - This sounds like something that could be checked later, so for me rather an Acceptance criteria.

- this component should be displayed on the page "savings: Would also be an Acceptance criteria for me, because it is well verifiable.

**Comment by sirtobiwan** [comment]
Thanks. I updated the user story accordingly

**Comment by REFAEI91** [comment]
LGTM👍🏻
