### ISSUE TITLE
US-7 - display annual power production and savings

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#15]
## Value proposition

As a user
I want to see the production of one solar panel at my location
in order to see the savings

## Description

![Image](https://user-images.githubusercontent.com/125971942/236849733-033def2d-255b-43ce-ad3b-255c9c786dcc.png)

## Acceptance criteria

- [ ] display power production per solar panel
- [ ] display annual savings on the same page

## Tasks

- [ ] import solar data from data component to saving component
- [ ] calculate and display correct data for one solar panel (data x 1,7)
- [ ] calculate and display savings (electricity costs x annual power production)

**Comment by HenrikeStahlhut** [comment]
LGTM ✌🏻
