### ISSUE TITLE
US-8 - Info box about a solar panel

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#16]
## Value proposition

As a user
I want to know the avg. size of a solar panel and the the orientation of the solar panel
in order to know the potnetial savings

## Description

![Bildschirm­foto 2023-05-10 um 18 12 39](https://github.com/sirtobiwan/Capstone-Project-Solar-Calculator/assets/125971942/fec909da-0880-4b89-92c6-5317afb7ed9b)

## Acceptance criteria

- [ ] click on info symbol 
- [ ] display info about solar panel size and about orientation

## Tasks

- [ ] implement a button/modal with an info symbol 
- [ ] the existing modal component can be used
- [ ] insert the new content at the savings component
- [ ] content should be: based on a regular solar panel with 1.700x1.000 mm and on a photovoltaic orientation of 30 degrees south
