### ISSUE TITLE
US ? - Enter location manually

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#17]
## Value proposition

As a user
I want to input my location manually
in order to get the radiation of my required location

## Description
![Bildschirm­foto 2023-05-05 um 18 52 26](https://user-images.githubusercontent.com/125971942/236519273-4a0236fe-1fc6-4d1e-b8d7-b4187f4ad1dd.png)

## Acceptance criteria

- [ ] user can enter location
- [ ] display the location

## Tasks

- [ ] need to check the guidance.
- [ ] Here are some infos:
- [ ] API Location mit Autocomplete Google (bis 25.000 klick free):
https://www.99darshan.com/posts/interactive-maps-using-nextjs-and-google-maps/
https://www.99darshan.com/posts/interactive-maps-using-nextjs-and-google-maps/
https://developers.google.com/maps/documentation/places/web-service/autocomplete?hl=de
Mapbox (bis 50.000 klicks free)
https://docs.mapbox.com/playground/geocoding/?search_text=fd&proximity=ip
- [ ] An easy way is a form with an input field, where I can type in my city. Then fetch an API (e.g. google geo api) to get longitude and lattitude what you will need for a second fetch to the radiation-API. I think this makes more sense because someone that lives in Berlin may be interested what the radiation in Dortmund is.
