### ISSUE TITLE
User Story 2 - Display Calculations

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#2]
## Value proposition

As a user
I want an elecricity calculation based on my location
in order to know my potential savings when investing in solar panels

## Description
![Bildschirm­foto 2023-04-25 um 16 31 30](https://user-images.githubusercontent.com/125971942/234310009-8b65aeae-e35b-45c9-979e-a48b6173f756.png)

## Acceptance criteria

- [ ] the header is displayed
- [ ] the latest electricity costs will be displayed 
- [ ] the annual radiation per m2
- [ ] the annual savings per m2

## Tasks

- [ ] create a branch
- [ ] create a card component
- [ ] the latest electricity costs will be displayed as a dummy for Germany (for now, maybe on a later stage there will be an api)
- [ ] take over the radiation data per m2 from the previous US
- [ ] calculate the annual savings (multiply radiation and costs)

**Comment by Sullynobugz** [comment]
Hi Tobias, 
in my opinion the page looks good and contains all necessary information. Maybe a navigation to previous and next pages would add to the usability.

**Comment by sirtobiwan** [comment]
Thanks. The navigation will be implemented on a later stage
