### ISSUE TITLE
US-9 Location from Dropdown menu

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#21]
## Value proposition

As a user
I want to choose the location
in order to get the radiation of the required location

## Description

![Image](https://github.com/sirtobiwan/Capstone-Project-Solar-Calculator/assets/125971942/be3af519-58fe-482e-8175-3e8534c7bb5d)

## Acceptance criteria

- [ ] user can chose location from a dropdown menu

##Tasks

 - [ ] Create new branch 
 - [ ] Create new component with a useState
 - [ ] Insert the different locations 
 - [ ] display the radiation at the return statement
 - [ ] Implement the component to the page
