### ISSUE TITLE
US-12 - Invest of solar panel

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#26]
## Value proposition

As a user
I want to get displayed more information about the implementation of solar panels
in order to understand how much money I can save on a longterm

## Description
![Bildschirm­foto 2023-05-12 um 10 51 12](https://github.com/sirtobiwan/Capstone-Project-Solar-Calculator/assets/125971942/7f13798f-62b2-4a6d-9e53-6264cdc2e9e0)

## Acceptance criteria

- [ ] display average invest cost for a solar panel
- [ ] display government support
- [ ] display longterm return of invest

## Tasks

- [ ] create a branch
- [ ] create a new component
- [ ] create 3 fields on that component: invest costs, government support and return of invest
- [ ] create a new page
- [ ] insert the component to the page

**Comment by CJAkkuec** [comment]
LGTM 🚀
