### ISSUE TITLE
US-? - Display live solar radiation of selected location

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#29]
## Value proposition

As a user
I want to see the live solar radiation
in order to know the solar radiation of the selected location

## Description

![Bildschirm­foto 2023-05-15 um 15 03 41](https://github.com/sirtobiwan/Capstone-Project-Solar-Calculator/assets/125971942/a834ecaf-83b6-4e6a-b015-1d44b9176fd4)

## Acceptance criteria

- [ ] display live solar radiation of the selected location

## Tasks

- [ ] create a new branche
- [ ] connect to the solar api
- [ ] safe state of latitude/longitude of the selected location (jotai?)
- [ ] request the live solar radiation at the api accordingly to latitude/longitude
- [ ] display the live solar radiation at the radiation component
