### ISSUE TITLE
User Story 3 - create data base for radiation data

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#4]
## Value proposition

As a user
I want to see the data of the radiation
in order to know the actual radiation data

## Description
![Bildschirm­foto 2023-04-25 um 17 44 40](https://user-images.githubusercontent.com/125971942/234331442-e2be44bb-0738-4a48-a69a-53ab8f766b68.png)

## Acceptance criteria

- [ ] the radiation data will be displayed

## Tasks

- [ ] fetch the data of the radiation (dummy data for Frankfurt). This data can be stored in a database (mongo db)
- [ ] calculate the data correctly -> Sum up the kW per one hour for a total of one year.
