### ISSUE TITLE
US-4 Display Next/Back Button on each page

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Capstone-Project-Solar-Calculator#8]
## Value proposition

As a use
I want to click on a next/back button
in order to get back to the previous page  or to the next page

## Description

NEXT Button
BACK Button

## Acceptance criteria

- [ ] back button display below the container on the left side
- [ ] next button display below the container on the right side

## Tasks

- [ ] create a button component
- [ ] implement the button component at the relevant pages
